# -*- coding: utf-8 -*-
"""Data Visualization and Correlation Analysis Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xs_bpIqLi2wQEV4FtF0qTPnvRDACgkqk

**Data Visualization and Correlation Analysis Project**

**# Reviewing the dataset**
"""

from google.colab import files
uploaded = files.upload()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import pearsonr

df = pd.read_csv("/content/Video_Game_Review_Dataset.csv")

df.head(10)

df.info()

df.describe()

# Checking Null values
df.isnull().sum()

"""**# Visualizations**"""

plt.figure(figsize=(10,6))

# Calculate quartiles and IQR
Q1 = df['Review Score'].quantile(0.25)
Q2 = df['Review Score'].median()
Q3 = df['Review Score'].quantile(0.75)

IQR = Q3 - Q1

# Theoretical limits
lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

# Actual whiskers
lower_whisker = df[df['Review Score'] >= lower_limit]['Review Score'].min()
upper_whisker = df[df['Review Score'] <= upper_limit]['Review Score'].max()

# Create boxplot
sns.boxplot(
    y=df['Review Score'],
    color='skyblue',
    width=0.3
)

# Labels
plt.text(0.1, Q1, f'Q1: {Q1:.2f}', color='blue')
plt.text(0.1, Q2, f'Median (Q2): {Q2:.2f}', color='red')
plt.text(0.1, Q3, f'Q3: {Q3:.2f}', color='blue')

plt.text(
    0.1,
    lower_whisker,
    f'Lower Whisker: {lower_whisker:.2f}',
    color='green'
)

plt.text(
    0.1,
    upper_whisker,
    f'Upper Whisker: {upper_whisker:.2f}',
    color='green'
)

# Title and labels
plt.title('Distribution of Review Scores', fontsize=14)
plt.ylabel('Review Score')

plt.grid(True)

plt.show()

# Print calculations
print("Q1:", round(Q1,2))
print("Median (Q2):", round(Q2,2))
print("Q3:", round(Q3,2))
print("IQR:", round(IQR,2))

print("\nTheoretical Limits:")
print("Lower Limit:", round(lower_limit,2))
print("Upper Limit:", round(upper_limit,2))

print("\nActual Whiskers:")
print("Lower Whisker:", round(lower_whisker,2))
print("Upper Whisker:", round(upper_whisker,2))

# Import required libraries

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df['Hours Played'].max()

# Groups Classification

df['Player Group'] = pd.qcut(
    df['Hours Played'],
    q=3,
    labels=['Beginner', 'Intermediate', 'Advanced']
)

# Check groups
print(df['Player Group'].value_counts())

plt.figure(figsize=(10,6))

sns.boxplot(
    x='Player Group',
    y='Review Score',
    data=df,
    palette='Set2'
)

plt.title('Review Scores Across Player Groups', fontsize=14)

plt.xlabel('Player Group')
plt.ylabel('Review Score')

plt.grid(True)

plt.show()

plt.figure(figsize=(10,6))

# Calculate quartiles and IQR
Q1 = df['Review Score'].quantile(0.25)
Q2 = df['Review Score'].median()
Q3 = df['Review Score'].quantile(0.75)

IQR = Q3 - Q1

# Theoretical limits
lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

# Actual whiskers
lower_whisker = df[df['Review Score'] >= lower_limit]['Review Score'].min()
upper_whisker = df[df['Review Score'] <= upper_limit]['Review Score'].max()

# Create boxplot
sns.boxplot(
    y=df['Review Score'],
    color='skyblue',
    width=0.3
)

# Labels
plt.text(0.1, Q1, f'Q1: {Q1:.2f}', color='blue')
plt.text(0.1, Q2, f'Median (Q2): {Q2:.2f}', color='red')
plt.text(0.1, Q3, f'Q3: {Q3:.2f}', color='blue')

plt.text(
    0.1,
    lower_whisker,
    f'Lower Whisker: {lower_whisker:.2f}',
    color='green'
)

plt.text(
    0.1,
    upper_whisker,
    f'Upper Whisker: {upper_whisker:.2f}',
    color='green'
)

# Title and labels
plt.title('Distribution of Review Scores', fontsize=14)
plt.ylabel('Review Score')

plt.grid(True)

plt.show()

# Print calculations
print("Q1:", round(Q1,2))
print("Median (Q2):", round(Q2,2))
print("Q3:", round(Q3,2))
print("IQR:", round(IQR,2))

print("\nTheoretical Limits:")
print("Lower Limit:", round(lower_limit,2))
print("Upper Limit:", round(upper_limit,2))

print("\nActual Whiskers:")
print("Lower Whisker:", round(lower_whisker,2))
print("Upper Whisker:", round(upper_whisker,2))

"""**# Correlation Analysis**"""

# Create Scatter Plot with Regression Line
plt.figure(figsize=(8,6))

sns.regplot(
    x='Hours Played',
    y='Review Score',
    data=df,
    scatter_kws={'s':70},
    line_kws={'color':'red'}
)

plt.title('Hours Played vs Review Score', fontsize=14)

plt.xlabel('Hours Played')
plt.ylabel('Review Score')

plt.grid(True)

plt.show()

# Pearson Correlation Analysis

corr, p_value = pearsonr(
    df['Hours Played'],
    df['Review Score']
)

print("Pearson Correlation Coefficient:", round(corr, 2))
print("P-value:", round(p_value, 4))

# Correlation Heat Map
plt.figure(figsize=(6,4))

sns.heatmap(
    df[['Hours Played', 'Review Score']].corr(),
    annot=True,
    cmap='coolwarm'
)

plt.title('Correlation Heatmap')

plt.show()